import type { BasicWanResponse } from '../../types/basicWan';

export const basicWanMockData: BasicWanResponse = {
  BasicWan: {
    ListIPv4Mode: ['dhcp4', 'ppp4', 'none', 'static'],
    ListOperationMode: ['Manual'],
    ListVLANType: ['untagged', 'tagged'],
    ListConnectionTrigger: ['OnDemand', 'AlwaysOn', 'Manual'],
    ListIPv6Mode: ['dhcp6', 'ppp6', 'none', 'static'],
    Interfaces: [
      {
        VLANPriority: 0,
        IPv4DefaultRouter: '',
        VLANType: 'untagged',
        Option12: 1,
        SLAAC: 1,
        IPv6DefaultRouter: '',
        HostName: 'OpenWRT',
        IPv6Address: '',
        IPv6PrefixLength: 64,
        IPv6DNSServers: '',
        Contrigger: '',
        IANA: 0,
        Option61: 1,
        IdleTime: 0,
        Interface: 'wan1',
        IPv4SubnetMask: '',
        VLANID: 100,
        VendorClassID: 'prpl dhcp',
        UserName: '',
        ServiceName: '',
        Password: '',
        IPv4Address: '',
        IAPD: 1,
        Option60: 1,
        IPv6Enable: 1,
        ClientID: '01D68C9A00AEFA',
        IPv4DNSServers: '',
        IPv4Enable: 1,
        MTU: 1500,
        IPv6Mode: 'dhcp6',
        IPv4Mode: 'dhcp4'
      },
      {
        VLANPriority: 0,
        IPv4DefaultRouter: '',
        VLANType: 'untagged',
        Option12: 1,
        SLAAC: 0,
        IPv6DefaultRouter: '',
        HostName: 'OpenWRT',
        IPv6Address: '',
        IPv6PrefixLength: 64,
        IPv6DNSServers: '',
        Contrigger: '',
        IANA: 0,
        Option61: 1,
        IdleTime: 0,
        Interface: 'wan2',
        IPv4SubnetMask: '',
        VLANID: 100,
        VendorClassID: 'prpl dhcp',
        UserName: '',
        ServiceName: '',
        Password: '',
        IPv4Address: '',
        IAPD: 0,
        Option60: 1,
        IPv6Enable: 0,
        ClientID: '',
        IPv4DNSServers: '',
        IPv4Enable: 1,
        MTU: 1500,
        IPv6Mode: 'none',
        IPv4Mode: 'dhcp4'
      }
    ]
  }
};
